# Makefile generated by ghake 3.0.1
# ghake by Ghassan Younes (www.ghassanyounes.com/ghake)
#
# MACROS ======================================================================

ERASE=rm -rf

EXE=ghake

OUTDIR=build/gnu/

MDEBUG=valgrind

MDARGS=-q --leak-check=full --show-reachable=yes --tool=memcheck --trace-children=yes   --suppressions=/home/ghassan/bin/false.supp

CC=g++

P=P

CFLAGS=-g -O0 -pedantic -Wall -Wextra -Werror -Wall -Wextra -Werror -Wconversion -Winline -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wcast-qual -Wswitch-default -Wswitch-enum -Wunreachable-code -Wduplicated-cond -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wpedantic -o 

OBJECTS=$(OUTDIR)compiler.o $(OUTDIR)doxygen.o $(OUTDIR)helpers.o $(OUTDIR)main.o $(OUTDIR)memdebug.o 

RUNARGS=--help

# TARGETS ======================================================================

: 
	echo -e ' --no-print-directory' | $(MAKE) run

run : $(OUTDIR)$(EXE) $(OBJECTS)
#	$(MAKE) doxygen
#	$(MAKE) memchk
	./$(OUTDIR)$(EXE) $(RUNARGS) 
	clear; echo "Made executable successfully. \
	You can find the built executable at $(OUTDIR)$(EXE)"

install : $(OUTDIR)$(EXE) $(OBJECTS)
	cp $(OUTDIR)$(EXE) /usr/bin/ghake

$(OUTDIR)$(EXE) : $(OBJECTS) makefile
	$(CC) $(OBJECTS) $(CFLAGS) $(OUTDIR)$(EXE)

$(OUTDIR)compiler.o: compiler.cpp functions.h
	$(CC) compiler.cpp -c $(CFLAGS) $(OUTDIR)compiler.o 

$(OUTDIR)doxygen.o: doxygen.cpp functions.h
	$(CC) doxygen.cpp -c $(CFLAGS) $(OUTDIR)doxygen.o 

$(OUTDIR)helpers.o: helpers.cpp functions.h
	$(CC) helpers.cpp -c $(CFLAGS) $(OUTDIR)helpers.o 

$(OUTDIR)main.o: main.cpp functions.h
	$(CC) main.cpp -c $(CFLAGS) $(OUTDIR)main.o 

$(OUTDIR)memdebug.o: memdebug.cpp functions.h
	$(CC) memdebug.cpp -c $(CFLAGS) $(OUTDIR)memdebug.o 

memchk : $(OUTDIR)$(EXE) $(OBJECTS)
	$(MDEBUG) $(MDARGS) $(OUTDIR)$(EXE) $(RUNARGS)

clean :
	@$(ERASE) $(OUTDIR)*

rebuild :
	$(MAKE) clean
	$(MAKE)

doxygen :
	-@$(ERASE) html/
	-@$(ERASE) latex/
	( cat Doxyfile ; echo "EXTRACT_ALL=YES" ) | doxygen -
	( cat Doxyfile ; echo "EXTRACT_ALL=NO" ) | doxygen -

doxyclean :
	-@$(ERASE) Doxyfile
	-@$(ERASE) html/
	-@$(ERASE) latex/
