compilation Namespace Reference
cout, cin, endl
Enumerations
enum COMPIL {
GCC,
GPP,
MICROSOFT,
CLANG,
CLANGPP,
UNIX,
ERR
 }
Functions
COMPIL compiler (std::string comp)
This function returns the compiler requested by the user.
std::string compilargs (COMPIL compiler)
This function returns the compiler requested by the user.
STATUS inject (COMPIL cc, std::string cliargs, std::string makename)
This function injects the compiler and arguments into the makefile.
Detailed Description
cout, cin, endl
Enumeration Type Documentation
COMPIL
enum compilation::COMPIL
Enumerator
GCC
GPP
MICROSOFT
CLANG
CLANGPP
UNIX
ERR
Definition at line 29 of file functions.h.
              {
    GCC,
    GPP,
    MICROSOFT,
    CLANG,
    CLANGPP,
    UNIX,
    ERR
  };
Function Documentation
compilargs()
std::string compilation::compilargs (COMPIL compiler)
This function returns the compiler requested by the user.
Parameters
compiler Compiler requested by the user
Returns
Returns the compiler arguments to be used (CS170 - ANSI C++ standards)
Definition at line 74 of file compile.cpp.
  {
    switch (compiler)
    {
    case GCC:
      return "-g -ansi -pedantic -Wall -Wextra -Werror -Wall -Wextra -Werror -Wconversion -Winline -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wcast-qual -Wswitch-default -Wswitch-enum -Wunreachable-code -Wduplicated-cond -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wpedantic -o \n";
      break;
    case GPP:
      return "-g -ansi -pedantic -Wall -Wextra -Werror -Wall -Wextra -Werror -Wconversion -Winline -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wcast-qual -Wswitch-default -Wswitch-enum -Wunreachable-code -Wduplicated-cond -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wpedantic -o \n";
      break;
    case MICROSOFT:
      return "-W4 -WX -EHa -Za -Fehw-ms.exe -D_CRT_SECURE_NO_DEPRECATE \n";
      break;
    case CLANG:
      return "-g -O0 -v -ansi -pedantic -Wall -Wextra -Werror -Wall -Wextra -Werror -Wconversion -Winline -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wcast-qual -Wswitch-default -Wswitch-enum -Wunreachable-code -Wduplicate-enum -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wpedantic -o \n"; //-c is applicable for .o generation
      break;
    case CLANGPP:
      return "-g -O0 -v -std=c++98 -pedantic -Wall -Wextra -Werror -Wall -Wextra -Werror -Wconversion -Winline -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wcast-qual -Wswitch-default -Wswitch-enum -Wunreachable-code -Wduplicate-enum -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wpedantic -o \n"; //-c is applicable for .o generation
      break;
    case UNIX:
      return " \n";
      break;
    case ERR:
      return "ERROR\n";
      break;
    
    default:
      return "ERROR\n";
      break;
    }
  }
References CLANG, CLANGPP, compiler(), ERR, GCC, GPP, MICROSOFT, and UNIX.
Referenced by main().
compiler()
COMPIL compilation::compiler (std::string comp)
This function returns the compiler requested by the user.
Parameters
comp Program executable input from argv[]
Returns
Returns the compiler being used
Definition at line 30 of file compile.cpp.
  {
    if (comp.compare("gcc") == 0)
    {
      return GCC;
    }
    else if (comp.compare("g++") == 0)
    {
      return GPP;
    }
    else if (comp.compare("cl") == 0)
    {
      return MICROSOFT;
    }
    else if (comp.compare("cc") == 0)
    {
      return UNIX;
    }
    else if(comp.compare("clang") == 0)
    {
      return CLANG;
    }
    else if(comp.compare("clang++") == 0)
    {
      return CLANGPP;
    }
    else
    {
      return ERR;
    }
  }
References CLANG, CLANGPP, ERR, GCC, GPP, MICROSOFT, and UNIX.
Referenced by compilargs(), basemake::generatedeps(), basemake::macros(), and main().
inject()
STATUS compilation::inject (COMPIL cc, std::string cliargs, std::string makename)
This function injects the compiler and arguments into the makefile.